#!/bin/bash
export PKG_CONFIG_DIR=
export PKG_CONFIG_PATH=
export PKG_CONFIG_LIBDIR="/home/taron/code/wiliwili/sysroot/usr/local/lib/pkgconfig:/home/taron/code/wiliwili/sysroot/usr/lib/aarch64-linux-gnu/pkgconfig:/home/taron/code/wiliwili/sysroot/usr/lib/pkgconfig:/home/taron/code/wiliwili/sysroot/usr/share/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="/home/taron/code/wiliwili/sysroot"
exec pkg-config "$@"
